//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class StationEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StationEntity()
        {
            this.WorkTimeEntity = new HashSet<WorkTimeEntity>();
        }
    
        public int StationId { get; set; }
        public string StationName { get; set; }
        public string Derscpion { get; set; }
        public int TeamEntityTeamEntityId { get; set; }
    
        public virtual TeamEntity teams { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkTimeEntity> WorkTimeEntity { get; set; }
    }
}
